### ISSUE TITLE
The core DevWorkspace API should be Che agnostic

### ISSUE THREAD

**Issue by l0rd** [devfile/kubernetes-api#5]
If other go projects want to add the devworkspace as a dependency they should be able to import only the core API. For instance `chePlugins` or `cheEditors` components should not be part of it.

**Comment by davidfestal** [comment]
When looking into how `chePlugin` components are defined, and especially, when looking into the schema of the `meta.yaml` file that defines a `chePluign`, we can see that it is very general and not that `Che` specific as it seems.
Renaming `chePlugin` to `plugin`, and `cheEditor` to `editor` may be a first step.

OTOH, we should probably bear in mind that the content of devfiles is mainly a description of the expected features of the workspace, but it doesn't pull any implementation.

So having some sort of components in the devfile schema that some consumer doesn't need should not be a problem. Not-needed component type could just be ignored, but it will not pull unnecessary implementation code.

**Comment by l0rd** [comment]
Closing this since the spec is currently che agnostic
