### ISSUE TITLE
How to set/override a container's entrypoint command/args?

### ISSUE THREAD

**Issue by johnmcollier** [devfile/kubernetes-api#50]
(More of a question than a user story)

In devfile 1.0, we were able to set a `dockerimage` component entrypoint command and args with the `command` and `args` field. A simple example might be:
```
  -
    type: dockerimage
    image: docker.io/someimage:latest
    alias: build
    memoryLimit: 512Mi
    command: ['tail']
    args: [ '-f', '/dev/null']
```

While working on the Devfile 2.0 integration in odo, @adisky noticed [there weren't equivalent fields for command and args in the container component](https://github.com/openshift/odo/pull/3198#discussion_r426585832), and I couldn't seem to find anything in the devfile 2.0 spec either:

<img width="1051" alt="Screen Shot 2020-05-19 at 10 14 51 AM" src="https://user-images.githubusercontent.com/6880023/82337620-fb292a80-99b9-11ea-8ead-06c475b39a4f.png">

Do we need those fields in devfile 2.0 (and therefore don't allow people to override a container's entrypoint) or was that an omission from the spec?

**Comment by elsony** [comment]
After talking to @l0rd, this is just an omission.

**Comment by davidfestal** [comment]
Should be fixed by PR https://github.com/devfile/kubernetes-api/pull/65

**Comment by l0rd** [comment]
Closing this issue since it should have been fixed now.
