### ISSUE TITLE
control over how rsync and start/stop happens

### ISSUE THREAD

**Issue by maxandersen** [devfile/kubernetes-api#60]
/kind feature

## Which functionality do you think we should add?

Being able to customize in devfile what folders are rsynced to not only support in-cluster source builds but be able to take locally built artifacts and put in a specific location on the deployment.

## Why is this needed?

to support wildfly, tomcat, nodejs or any other runtime that supports true incremental hotdeploy of  resources (wether source or binaries) (quarkus will support this in upcoming releases)

Advantages:
- speed - allows us to fully skip the in cluster build.
- experimentation - one can do local changes and experiments not necessarily encoded in pom.xml etc. yet
- local vs remote are in sync; less surprises during development
- can be used to focus source based builds too to save time

disadvantages:
- makes non-reproducible builds (but that is the same today where you don't need to commit to see changes)

originally opened at https://github.com/openshift/odo/issues/3132 but asked to also open here.

**Comment by l0rd** [comment]
Volume is the mechanism that allow sharing files amongst components of a Devfile ([see the v2.0 issue about that](https://github.com/devfile/kubernetes-api/issues/19)). And [`mountSources: true`](https://github.com/devfile/kubernetes-api/issues/17) is a simple way to include sources (i.e. `projects`) in a component.

**Comment by l0rd** [comment]
Closing this as the specification of folders to share is done with volumes and the hot reload part is tracked in #64
