### ISSUE TITLE
hooks for local configuration/override of toolchain

### ISSUE THREAD

**Issue by maxandersen** [devfile/kubernetes-api#63]
Provide metadata or environment variables for common commands across runtimes. For example 'APPLICATION_TEST_COMMAND=npm test'.
[ shoubhik ] Are these analogous to commands in the devfiile https://che-devfile-registry.openshift.io//devfiles/angular/devfile.yaml ?

 lifecycle “hooks" for an AppStack or Devfile based application. For example, CLI tooling should be able to inject actions during each phase of an application's lifecycle - initialize, local execution, build, and deployment.

/cc @lance

**Comment by l0rd** [comment]
@maxandersen @lance we have described the lifecycle events and how to associate commands to them in this issuse: #32. This is part of the v2 spec. Does that help with your use case?

**Comment by metacosm** [comment]
Could you elaborate on what this is attempting to do, @maxandersen? I'm not seeing how different this is from specifying commands?

**Comment by maxandersen** [comment]
#32 looks like what I understood @lance was after but best he confirms. 

@metacosm difference to commands are you can add actions "locally" rather than override what is coming from catalog.

**Comment by lance** [comment]
After looking at #32 I'm not 100% sure what the implementation will look like, but the general direction is in line with the use case. Thanks!

**Comment by l0rd** [comment]
Closing as lifecycle events described in #32 should address this use case.
